### ISSUE TITLE
0.3.2: FTBFS with consul-0.6.4

### ISSUE THREAD

**Issue by onlyjob** [hashicorp/nomad#1127]
Nomad 0.3.2 FTBFS when built with Consul 0.6.4:

~~~~
# github.com/hashicorp/nomad/client/consul 
src/github.com/hashicorp/nomad/client/consul/sync.go:90: undefined: api.TLSConfig 
src/github.com/hashicorp/nomad/client/consul/sync.go:97: undefined: api.SetupTLSConfig 
src/github.com/hashicorp/nomad/client/consul/sync.go:432: undefined: api.HealthCritical 
src/github.com/hashicorp/nomad/client/consul/sync.go:436: undefined: api.HealthPassing 
src/github.com/hashicorp/nomad/client/consul/sync.go:438: undefined: api.HealthWarning 
src/github.com/hashicorp/nomad/client/consul/sync.go:440: undefined: api.HealthCritical 
src/github.com/hashicorp/nomad/client/consul/sync.go:443: undefined: api.HealthCritical 
~~~~

Also please vendor tagged releases whenever possible. Thanks.

**Comment by onlyjob** [comment]
This is regression from v0.3.1 which builds fine with Consul-0.6.4.

**Comment by diptanu** [comment]
@onlyjob We have vendored the consul API related dependencies with Nomad so it should build fine if you are using Go 1.6. The reason why we had to depend on a particular version from the master post Consul 0.6.4 is we added some helper methods on the Consul API library after we released 0.6.4 and we didn't want to do another point release of Consul just for this.

**Comment by onlyjob** [comment]
I appreciate your explanation but that kind of bug handling is not helpful. Let's close bugs when problems are fixed please.

> we added some helper methods in the Consul API library after we released 0.6.4 and we didn't want to do another point release of Consul just for this.

You have to do point releases if another software depends on new functionality. It is necessary to vendor only released tags and avoid vendoring unreleased snapshots.

Please read about versioning from the following pages:

 * http://semver.org/
 * https://en.wikipedia.org/wiki/Software_versioning
 * [Debian Upstream Guide](https://wiki.debian.org/UpstreamGuide#Releases_and_Versions).

There are practical implications of sloppy vendoring: at the moment it is not possible to build official Debian package of Nomad-0.3.2 with Golang 1.6 due to above errors.

Proper versioning is important to formalise dependencies between packages.

**Comment by diptanu** [comment]
@onlyjob Sorry about that, we do point release of our software whenever we release anything changes. In this case, this was the consul API client which changed, and we had tested against a specific `sha` on consul's master branch which had the feature we needed. 

Often we have to update dependencies of Nomad which comes from other projects and it's not always possible to coordinate the release process of all our dependencies.

Having said that, I still don't understand why your build is failing if you have nothing else in your GOPATH but Nomad, and if you are using go 1.6, you should be able to build nomad successfully.

**Comment by onlyjob** [comment]
Versioning exist exactly to mark API changes so on this instance it was not used properly.

I suppose coordinating tag of the next version is relatively easy when we are talking about yet another Hashicorp project. Most likely opening a bug report "please tag new release" would be sufficient. Usually it works well enough with other projects that version their releases.

Build failure we've experienced is due to fact that in Debian we do not use vendored libraries. Instead we re-use system libraries that are packaged separately. Build dependencies are expressed using versions so on this instance we could not satisfy build dependency of Nomad because its v0.3.2 depends on unreleased snapshot of Consul.
Needless to say this problem is holding update of Nomad 0.3.1 in Debian... :(
